export const htmlLangList = [
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af-ZA",
        specCulture:"af-ZA",
        englishName:"Afrikaans (South Africa)"
    },
    {
        culture:"ar",
        specCulture:"ar-SA",
        englishName:"Arabic"
    },
    {
        culture:"ar-AE",
        specCulture:"ar-AE",
        englishName:"Arabic (U.A.E.)"
    },
    {
        culture:"ar-BH",
        specCulture:"ar-BH",
        englishName:"Arabic (Bahrain)"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
]