export const htmlLangList = [
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af-ZA",
        specCulture:"af-ZA",
        englishName:"Afrikaans (South Africa)"
    },
    {
        culture:"ar",
        specCulture:"ar-SA",
        englishName:"Arabic"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
    {
        culture:"af",
        specCulture:"af-ZA",
        englishName:"Afrikaans"
    },
]